#!/usr/bin/env node
import peggy from 'peggy';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const grammarFile = join(process.cwd(), 'src/grammar/compact.pegjs');
const outputFile = join(process.cwd(), 'src/parser-generated.js');

if (!existsSync(grammarFile)) {
  console.error(`Grammar file not found: ${grammarFile}`);
  process.exit(1);
}

try {
  const grammar = readFileSync(grammarFile, 'utf8');
  const parserSource = peggy.generate(grammar, {
    output: 'source',
    format: 'es',
  });

  const generated = `// Generated by Peggy\n// Source: src/grammar/compact.pegjs\n// Generated: ${new Date().toISOString()}\n// DO NOT EDIT - run 'npm run generate-parser' to regenerate\n\n${parserSource}\n`;

  writeFileSync(outputFile, generated, 'utf8');
  console.log(`Generated parser: ${outputFile}`);
} catch (error) {
  const err = error instanceof Error ? error : new Error(String(error));
  console.error(`Failed to generate parser: ${err.message}`);
  process.exit(1);
}
